version: 2.1

# 共通の実行イメージをexecutorとして定義
executors:
  default:
    docker:
      - image: circleci/ruby:2.7.1-buster
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
          TZ: Asia/Tokyo
    working_directory: ~/dev-memo-server
    environment:
      TZ: Asia/Tokyo

# Job間で共通する実行コマンドをcommandsとして定義
commands:
  install_bundler:
    steps:
      - run:
          name: Bundle Install Dependencies
          command: |
            gem install bundler:2.1.4
jobs:
  fetch_source_code:
    executor:
      name: default
    steps:
      - checkout
      - save_cache:
          key: v1-dev-memo-server-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/dev-memo-server

  bundle_dependencies:
    executor:
      name: default
    steps:
      - restore_cache: # ソースコードの復元
          key: v1-dev-memo-server-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Bundle Install Dependencies
          command: |
            bundle install
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  rubocop:
    executor:
      name: default
    steps:
      - restore_cache: # ソースコードの復元
          key: v1-dev-memo-server-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # vendor/bundleを復元
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Checking source code by rubocop
          command: |
            bundle exec rubocop --format fuubar
  rspec:
    executor:
      name: default
    steps:
      - restore_cache: # ソースコードの復元
          key: v1-dev-memo-server-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # vendor/bundleを復元
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Watting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Database Setup
          command: |
            mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: Testing DB Migration and Seed
          command: |
            bundle exec rake db:create db:migrate db:seed db:drop
      - run:
          name: Run RSpec
          command: |
            mkdir /tmp/test-results
            bundle exec rake db:create db:migrate
            mkdir -p ~/rspec
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --require rails_helper \
                              --color \
                              --format progress \
                              --format RspecJunitFormatter \
                              --out ~/rspec/rspec.xml
      # collect reports
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: /tmp/test-results
          destination: build

workflows:
  build:
    jobs:
      - fetch_source_code
      - bundle_dependencies:
          requires:
            - fetch_source_code
      - rspec:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
