version: "3.2"

services:
  database:
    restart: always
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-datavolume:/var/lib/mysql
      - ./docker/mysql-confd:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle install --quiet &&
        bundle exec rails s -p 3300 -b '0.0.0.0'
      "
    ports:
      - "3000:3000"
    volumes:
      - .:/dev-memo-server
      - "bundle:/usr/local/bundle"
    depends_on:
      - database
    tty: true
    stdin_open: true

volumes:
  bundle:
    driver: local
  mysql-datavolume:
    driver: local
